//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actris.Abstraction.Model.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ActrisContext : DbContext
    {
        public ActrisContext()
            : base("name=ActrisContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MD_ActionTrackingSource> MD_ActionTrackingSource { get; set; }
        public virtual DbSet<MD_CorrectiveActionFlowStatus> MD_CorrectiveActionFlowStatus { get; set; }
        public virtual DbSet<MD_CorrectiveActionImpactAnalysis> MD_CorrectiveActionImpactAnalysis { get; set; }
        public virtual DbSet<MD_CorrectiveActionOverdueImpact> MD_CorrectiveActionOverdueImpact { get; set; }
        public virtual DbSet<MD_CorrectiveActionPriority> MD_CorrectiveActionPriority { get; set; }
        public virtual DbSet<TX_ActionTracking> TX_ActionTracking { get; set; }
        public virtual DbSet<TX_CorrectiveAction> TX_CorrectiveAction { get; set; }
        public virtual DbSet<TX_CorrectiveActionHistory> TX_CorrectiveActionHistory { get; set; }
        public virtual DbSet<TX_CorrectiveActionUser> TX_CorrectiveActionUser { get; set; }
        public virtual DbSet<VW_ActionTrackingReport> VW_ActionTrackingReport { get; set; }
    }
}
