//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actris.Abstraction.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_CorrectiveActionFlowStatus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MD_CorrectiveActionFlowStatus()
        {
            this.MD_CorrectiveActionFlowStatus1 = new HashSet<MD_CorrectiveActionFlowStatus>();
            this.MD_CorrectiveActionFlowStatus11 = new HashSet<MD_CorrectiveActionFlowStatus>();
            this.MD_CorrectiveActionFlowStatus3 = new HashSet<MD_CorrectiveActionFlowStatus>();
        }
    
        public string CorrectiveActionFlowStatusID { get; set; }
        public string CorrectiveActionFlowStatusPendingID { get; set; }
        public string FlowCode { get; set; }
        public string FlowDesc { get; set; }
        public string FlowRole { get; set; }
        public string FlowRoleCode { get; set; }
        public string DataStatus { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MD_CorrectiveActionFlowStatus> MD_CorrectiveActionFlowStatus1 { get; set; }
        public virtual MD_CorrectiveActionFlowStatus MD_CorrectiveActionFlowStatus2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MD_CorrectiveActionFlowStatus> MD_CorrectiveActionFlowStatus11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MD_CorrectiveActionFlowStatus> MD_CorrectiveActionFlowStatus3 { get; set; }
    }
}
