//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actris.Abstraction.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_CorrectiveActionPriority
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MD_CorrectiveActionPriority()
        {
            this.TX_CorrectiveAction = new HashSet<TX_CorrectiveAction>();
        }
    
        public string CorrectiveActionPriorityID { get; set; }
        public string PriorityTitle { get; set; }
        public string PriorityValue { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string DataStatus { get; set; }
        public string PriorityTitle2 { get; set; }
        public string PriorityValue2 { get; set; }
        public Nullable<int> PriorityDuration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TX_CorrectiveAction> TX_CorrectiveAction { get; set; }
    }
}
