//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actris.Abstraction.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MD_CorrectiveActionImpactAnalysis
    {
        public string CorrectiveActionImpactAnalysisID { get; set; }
        public string AnalysisTitle { get; set; }
        public string AnalysisValue { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string DataStatus { get; set; }
        public string AnalysinTitle2 { get; set; }
        public string AnalysisValue2 { get; set; }
    }
}
