//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actris.Abstraction.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX_ActionTracking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TX_ActionTracking()
        {
            this.TX_CorrectiveAction = new HashSet<TX_CorrectiveAction>();
        }
    
        public string ActionTrackingID { get; set; }
        public string LocationStatusID { get; set; }
        public string ActionTrackingSourceID { get; set; }
        public string ObservationID { get; set; }
        public string ActionTrackingReference { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string FindingDesc { get; set; }
        public string LocationID { get; set; }
        public string Location { get; set; }
        public string SubLocation { get; set; }
        public string Nct { get; set; }
        public string Rca { get; set; }
        public string Status { get; set; }
        public string DataStatus { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string AttachementData { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public string AdditionalData { get; set; }
        public string TrypeShuRegion { get; set; }
        public string DirectorateRegionalID { get; set; }
        public string DirectorateRegionalDesc { get; set; }
        public string DivisiZonaID { get; set; }
        public string DivisiZonaDesc { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string WilayahkerjaID { get; set; }
        public string WilayahkerjaDesc { get; set; }
        public Nullable<bool> IsConfidential { get; set; }
    
        public virtual MD_ActionTrackingSource MD_ActionTrackingSource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TX_CorrectiveAction> TX_CorrectiveAction { get; set; }
    }
}
