//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actris.Abstraction.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TX_CorrectiveAction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TX_CorrectiveAction()
        {
            this.TX_CorrectiveActionHistory = new HashSet<TX_CorrectiveActionHistory>();
            this.TX_CorrectiveActionUser = new HashSet<TX_CorrectiveActionUser>();
        }
    
        public string CorrectiveActionID { get; set; }
        public string CorrectiveActionOverdueImpactID { get; set; }
        public string ActionTrackingID { get; set; }
        public string CorrectiveActionPriorityID { get; set; }
        public string CorrectiveActionReference { get; set; }
        public string ResponsibleDivision { get; set; }
        public string ResponsibleDivisionID { get; set; }
        public string ResponsibleDepartment { get; set; }
        public string ResponsibleDepartmentID { get; set; }
        public string ResponsibleManager { get; set; }
        public string ResponsibleManagerApprover { get; set; }
        public string ResponsibleManagerUsername { get; set; }
        public string ResponsibleDepartmentData { get; set; }
        public string Recomendation { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> ProposedDueDate { get; set; }
        public string ProposedDueDateApprover { get; set; }
        public string ProposedDueDateData { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string PicData { get; set; }
        public string AttachmentData { get; set; }
        public string FollowUpData { get; set; }
        public string OverdueData { get; set; }
        public string AdditionalData { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedAt { get; set; }
        public string Status { get; set; }
        public string DataStatus { get; set; }
        public string FlowCode { get; set; }
        public string TransID { get; set; }
    
        public virtual MD_CorrectiveActionOverdueImpact MD_CorrectiveActionOverdueImpact { get; set; }
        public virtual MD_CorrectiveActionPriority MD_CorrectiveActionPriority { get; set; }
        public virtual TX_ActionTracking TX_ActionTracking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TX_CorrectiveActionHistory> TX_CorrectiveActionHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TX_CorrectiveActionUser> TX_CorrectiveActionUser { get; set; }
    }
}
