//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actris.Abstraction.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ActionTrackingReport
    {
        public string ActionTrackingID { get; set; }
        public string CorrectiveActionID { get; set; }
        public string ActionID { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string ActSource { get; set; }
        public string ReferenceID { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string FindingDesc { get; set; }
        public string TypeShuRegion { get; set; }
        public string DirectorateRegionalDesc { get; set; }
        public string DivisiZonaDesc { get; set; }
        public string CompanyName { get; set; }
        public string WilayahkerjaDesc { get; set; }
        public string Location { get; set; }
        public string SubLocation { get; set; }
        public string Nct { get; set; }
        public string Rca { get; set; }
        public string CaID { get; set; }
        public string PendingAction { get; set; }
        public string StatusAction { get; set; }
        public string LastAction { get; set; }
        public Nullable<System.DateTime> LastActionDate { get; set; }
        public string PriorityTitle { get; set; }
        public string Recomendation { get; set; }
        public string ResponsibleDepartment { get; set; }
        public string ResponsibleManager { get; set; }
        public string Pic1 { get; set; }
        public string Pic2 { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> ProposedDueDate { get; set; }
        public string Justification { get; set; }
        public System.DateTime OverDueDate { get; set; }
        public Nullable<int> CumulativeOverdueDay { get; set; }
        public string OverdueReason { get; set; }
        public string OverdueImpact { get; set; }
        public string OverdueMitigation { get; set; }
        public string PlanCA { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string ActionTrackingReference { get; set; }
        public string AdditionalData { get; set; }
        public string SubdivisiDesc { get; set; }
        public string DepartementDesc { get; set; }
    }
}
