//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actris.Abstraction.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class LG_CorrectiveActionHistory
    {
        public string CorrectiveActionHistoryID { get; set; }
        public string CorrectiveActionID { get; set; }
        public string Action { get; set; }
        public string ActionBy { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string NextAction { get; set; }
        public string NextActionBy { get; set; }
        public string Note { get; set; }
        public string DataStatus { get; set; }
    
        public virtual TX_CorrectiveAction TX_CorrectiveAction { get; set; }
    }
}
