//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actris.Abstraction.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_PSAHierarchy
    {
        public string EntityID { get; set; }
        public string EntityName { get; set; }
        public string EntityType { get; set; }
        public string EntityParentID { get; set; }
        public Nullable<int> EntityLevel { get; set; }
        public string HierLvl1 { get; set; }
        public string HierLvl1Desc { get; set; }
        public string HierLvl1Type { get; set; }
        public string HierLvl2 { get; set; }
        public string HierLvl2Desc { get; set; }
        public string HierLvl2Type { get; set; }
        public string HierLvl3 { get; set; }
        public string HierLvl3Desc { get; set; }
        public string HierLvl3Type { get; set; }
        public string HierLvl4 { get; set; }
        public string HierLvl4Desc { get; set; }
        public string HierLvl4Type { get; set; }
        public string HierLvl5 { get; set; }
        public string HierLvl5Desc { get; set; }
        public string HierLvl5Type { get; set; }
        public string HierLvl6 { get; set; }
        public string HierLvl6Desc { get; set; }
        public string HierLvl6Type { get; set; }
        public string HierLvl7 { get; set; }
        public string HierLvl7Desc { get; set; }
        public string HierLvl7Type { get; set; }
        public string HierLvl8 { get; set; }
        public string HierLvl8Desc { get; set; }
        public string HierLvl8Type { get; set; }
        public string HierLvl9 { get; set; }
        public string HierLvl9Desc { get; set; }
        public string HierLvl9Type { get; set; }
        public string HierLvl10 { get; set; }
        public string HierLvl10Desc { get; set; }
        public string HierLvl10Type { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Remarks { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string PersAreaID { get; set; }
        public string PersSubAreaID { get; set; }
        public string TreeEntityID { get; set; }
        public string TreeEntityName { get; set; }
        public Nullable<System.DateTime> ETLCreatedDate { get; set; }
        public Nullable<System.DateTime> ETLChangedDate { get; set; }
        public string DirectorateID { get; set; }
        public string DirectorateDesc { get; set; }
        public string DivisionID { get; set; }
        public string DivisionDesc { get; set; }
    }
}
